//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.06 at 12:29:27 PM ICT 
//


package generalinfo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CLAIMNO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="POLICYNO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CPOLICYNO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="INSURANCETYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CLAIMNOTINO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="INSUREDNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CREATEDDATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CREATEDTIME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="COSI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DATEOFLOSS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TIMEOFLOSS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="INFORMERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ERRORCODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ERRORMESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CARTHIRDPARTY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "claimno",
    "policyno",
    "cpolicyno",
    "insurancetype",
    "claimnotino",
    "insuredname",
    "createddate",
    "createdtime",
    "cosi",
    "dateofloss",
    "timeofloss",
    "informername",
    "errorcode",
    "errormessage",
    "carthirdparty"
})
@XmlRootElement(name = "GetGeneralInfoResponse")
public class GetGeneralInfoResponse {

    @XmlElement(name = "CLAIMNO", required = true)
    protected String claimno;
    @XmlElement(name = "POLICYNO", required = true)
    protected String policyno;
    @XmlElement(name = "CPOLICYNO", required = true)
    protected String cpolicyno;
    @XmlElement(name = "INSURANCETYPE", required = true)
    protected String insurancetype;
    @XmlElement(name = "CLAIMNOTINO", required = true)
    protected String claimnotino;
    @XmlElement(name = "INSUREDNAME", required = true)
    protected String insuredname;
    @XmlElement(name = "CREATEDDATE", required = true)
    protected String createddate;
    @XmlElement(name = "CREATEDTIME", required = true)
    protected String createdtime;
    @XmlElement(name = "COSI", required = true)
    protected String cosi;
    @XmlElement(name = "DATEOFLOSS", required = true)
    protected String dateofloss;
    @XmlElement(name = "TIMEOFLOSS", required = true)
    protected String timeofloss;
    @XmlElement(name = "INFORMERNAME", required = true)
    protected String informername;
    @XmlElement(name = "ERRORCODE", required = true)
    protected String errorcode;
    @XmlElement(name = "ERRORMESSAGE", required = true)
    protected String errormessage;
    @XmlElement(name = "CARTHIRDPARTY", required = true)
    protected String carthirdparty;

    /**
     * Gets the value of the claimno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLAIMNO() {
        return claimno;
    }

    /**
     * Sets the value of the claimno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLAIMNO(String value) {
        this.claimno = value;
    }

    /**
     * Gets the value of the policyno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLICYNO() {
        return policyno;
    }

    /**
     * Sets the value of the policyno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLICYNO(String value) {
        this.policyno = value;
    }

    /**
     * Gets the value of the cpolicyno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPOLICYNO() {
        return cpolicyno;
    }

    /**
     * Sets the value of the cpolicyno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPOLICYNO(String value) {
        this.cpolicyno = value;
    }

    /**
     * Gets the value of the insurancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSURANCETYPE() {
        return insurancetype;
    }

    /**
     * Sets the value of the insurancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSURANCETYPE(String value) {
        this.insurancetype = value;
    }

    /**
     * Gets the value of the claimnotino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLAIMNOTINO() {
        return claimnotino;
    }

    /**
     * Sets the value of the claimnotino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLAIMNOTINO(String value) {
        this.claimnotino = value;
    }

    /**
     * Gets the value of the insuredname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSUREDNAME() {
        return insuredname;
    }

    /**
     * Sets the value of the insuredname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSUREDNAME(String value) {
        this.insuredname = value;
    }

    /**
     * Gets the value of the createddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDDATE() {
        return createddate;
    }

    /**
     * Sets the value of the createddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDDATE(String value) {
        this.createddate = value;
    }

    /**
     * Gets the value of the createdtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDTIME() {
        return createdtime;
    }

    /**
     * Sets the value of the createdtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDTIME(String value) {
        this.createdtime = value;
    }

    /**
     * Gets the value of the cosi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSI() {
        return cosi;
    }

    /**
     * Sets the value of the cosi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSI(String value) {
        this.cosi = value;
    }

    /**
     * Gets the value of the dateofloss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEOFLOSS() {
        return dateofloss;
    }

    /**
     * Sets the value of the dateofloss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEOFLOSS(String value) {
        this.dateofloss = value;
    }

    /**
     * Gets the value of the timeofloss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEOFLOSS() {
        return timeofloss;
    }

    /**
     * Sets the value of the timeofloss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEOFLOSS(String value) {
        this.timeofloss = value;
    }

    /**
     * Gets the value of the informername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFORMERNAME() {
        return informername;
    }

    /**
     * Sets the value of the informername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFORMERNAME(String value) {
        this.informername = value;
    }

    /**
     * Gets the value of the errorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORCODE() {
        return errorcode;
    }

    /**
     * Sets the value of the errorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORCODE(String value) {
        this.errorcode = value;
    }

    /**
     * Gets the value of the errormessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORMESSAGE() {
        return errormessage;
    }

    /**
     * Sets the value of the errormessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORMESSAGE(String value) {
        this.errormessage = value;
    }

    /**
     * Gets the value of the carthirdparty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCARTHIRDPARTY() {
        return carthirdparty;
    }

    /**
     * Sets the value of the carthirdparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCARTHIRDPARTY(String value) {
        this.carthirdparty = value;
    }

}
